---
- hosts: kube_control_plane
  gather_facts: true
  roles:
    - role: update_and_upgrade_os
      become: yes
    - role: install_containerd
      become: yes
    - role: install_kubernetes
      become: yes
    - role: configure_kubeadm
    - role: copy_kubeconfig
