---
- hosts: kube_node[1]
  gather_facts: true
  roles:
    - role: update_and_upgrade_os
      become: yes
    - role: install_containerd
      become: yes
    - role: install_kubernetes
      become: yes
